# Maven
# Build your Java project and run tests with Apache Maven.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

trigger:
- none

pool:
  name: "Self Hosted Pool"
  #vmImage: ubuntu-latest

variables:
- group: pipeline_vars

steps:
- task: Maven@3
  inputs:
    mavenPomFile: 'pom.xml'
    mavenOptions: '-Xmx3072m'
    #javaHomeOption: 'JDKVersion'
    #jdkVersionOption: '1.833'
    #jdkArchitectureOption: 'x64'
    publishJUnitResults: true
    testResultsFiles: '**/surefire-reports/TEST-*.xml'
    goals: 'package'

- task: Docker@2
  inputs:
    containerRegistry: 'dockerhub-AZ'
    repository: 'docker4028/numeric-app'
    command: 'buildandpush'
    Dockerfile: 'Dockerfile'
    tags: $(Build.BuildId)
  

- task: KubernetesManifest@0
  inputs:
    action: 'deploy'
    kubernetesServiceConnection: 'k8s-az-con'
    namespace: 'dev-fargate'
    #namespace: 'default'
    manifests: |
      k8s-app-manifests/numericapp_deployment.yaml
      k8s-app-manifests/numericapp_svc.yaml
    #imagePullSecrets: 'dockerregcredsaz'
    imagePullSecrets: 'dokrregdevops'