apiVersion: v1
kind: Service
metadata:
  labels:
    app: {{ .Values.DevApp.app }}
  name: {{ .Values.Service.name }}
spec:
  ports:
  - port: {{ .Values.Service.port }}
    protocol: {{ .Values.Service.protocol }}
    targetPort: {{ .Values.Service.targetPort }}
  selector:
    app: {{ .Values.DevApp.app }}
  type: {{ .Values.Service.type }} 

